NIAD-2023: Template Mapper
NHSDigital/nia-patient-switching-standard-adaptor pull request #101
Opened 2022-03-08 20:17 UTC by rorysproule2

2022-03-11 16:18 UTC, mrogowska requested changes
It might be good if you and Elliot decide whose PR will be merged first, as Elliot's done some cleanup in his, and there will be some sad conflicts :(

2022-03-11 16:18 UTC, mrogowska commented on gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/BundleMapperService.java
> +        return templateMapper.mapTemplates(ehrExtract, patient, encounters, practiseCode);
I don't think this method is needed, you can just call `templateMapper.mapTemplates(ehrExtract, patient, encounters, practiseCode);` inside mapToBundle method. (Elliot is doing the cleanup like this in his PR so it'll be nice to keep it consistent from now on)

2022-03-14 08:06 UTC, mrogowska submitted a review, later dismissed

2022-03-14 10:05 UTC, mrogowska approved these changes

2022-03-14 10:13 UTC, bchotkowski approved these changes

2022-03-14 10:14 UTC, merged