Niad 1924 jenkins code to upload pss image
NHSDigital/nia-patient-switching-standard-adaptor pull request #14
Opened 2021-12-07 14:20 UTC by Tyler-34

2021-12-07 16:59 UTC, RIashfaqahmed approved these changes

2021-12-08 09:21 UTC, mrogowska requested changes

2021-12-08 09:21 UTC, mrogowska commented on Jenkinsfile
> +                /*stage('Tests') {
Could you uncomment this stage? Or remove it if it's not used?

2021-12-08 09:27 UTC, mrogowska approved these changes

2021-12-08 10:08 UTC, RIashfaqahmed approved these changes

2021-12-08 10:08 UTC, merged