NIAD-2147: fix failing tests and merge with current main code ready f…
NHSDigital/nia-patient-switching-standard-adaptor pull request #167
Opened 2022-05-27 15:17 UTC by hodge70

…or review.

Fixed violations, failing tests and affected main branch logic now appears to funciton as required.  All tests passed from local gradle run.

2022-06-01 12:55 UTC, benhession requested changes

2022-06-01 12:55 UTC, benhession commented on gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/COPCMessageHandler.java
> +        if (currentAttachmentLog == null || currentAttachmentLog.getParentMid() == null) {
There's a conflict here with the logic on line 123. Changes were brought in with NIAD-2156.

2022-06-01 12:55 UTC, benhession commented on gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/COPCMessageHandler.java
> +        var canCheckAttachmentLength = false;
Doesn't the check on line 112 ensure canCheckAttachmentLength is never false?

2022-06-01 12:55 UTC, benhession commented on gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/COPCMessageHandlerTest.java
> +
Have you left this whitespace here by mistake?

2022-06-09 06:34 UTC, mrogowska reviewed
Checkstyle is failing: `/home/gradle/service/gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/COPCMessageHandler.java:171:37: '{' is not preceded with whitespace.`

2022-06-09 06:34 UTC, mrogowska commented on gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/COPCMessageHandlerTest.java
> +        //? ASSERT
why `//?`

2022-06-13 23:44 UTC, closed without merging