Necessary code changes and changes to expected test values.
NHSDigital/nia-patient-switching-standard-adaptor pull request #229
Opened 2023-01-25 17:04 UTC by dfk97

2023-01-26 14:03 UTC, SRAlexander requested changes
Looks like there's an issue with some of the data, I'll re-review once corrected

2023-01-26 14:03 UTC, SRAlexander commented on gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario6.json
> -              "valueId": "254076013"
This is another one that seems to be a valid code for the given text

2023-02-02 09:06 UTC, SRAlexander requested changes

2023-02-02 09:06 UTC, SRAlexander commented on gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json
> -              "valueId": "127639017"
This is also a valid description id and should be present

2023-02-02 09:06 UTC, SRAlexander commented on gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json
> -        "value": "{{LOCATION-2}}"
We need these tags to remain the same

2023-02-02 09:06 UTC, SRAlexander commented on gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json
> -              "valueId": "64172013"
ID matches the description text, this should be present

2023-02-02 09:06 UTC, SRAlexander commented on gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json
> -              "valueId": "249995012"
Valid description id, it looks like we've got a pattern here in that we're losing descriptionId's against valid description text. Investigation required.

2023-02-06 09:01 UTC, SRAlexander approved these changes
Found cases all seem to be fixed, I've reviewed 6 of the test files with no issues found. That is a good indicator that we have covered all cases.

2023-02-07 14:02 UTC, SRAlexander submitted a review, later dismissed

2023-02-07 14:29 UTC, SRAlexander approved these changes

2023-02-07 14:53 UTC, benhession commented on gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json
>          "status": "current",
Why is the related problem removed here?

2023-02-07 14:53 UTC, benhession commented on gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json
>            ]
should there be an extra bracket here?

2023-02-07 14:53 UTC, benhession commented on gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json
>            ]
Extra bracket again.

2023-02-07 14:53 UTC, benhession commented on gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP11-output.json
>            ]
bracket

2023-02-08 10:05 UTC, SRAlexander approved these changes

2023-02-08 10:06 UTC, merged