NIAD-1880: Send EHRExtract request
NHSDigital/nia-patient-switching-standard-adaptor pull request #24
Opened 2022-01-13 12:51 UTC by bchotkowski

Story -> [NIAD-1880](https://gpitbjss.atlassian.net/browse/NIAD-1880)

2022-01-27 14:33 UTC, bbell-kainos submitted a review, later dismissed

2022-01-28 10:19 UTC, rorysproule1 submitted a review, later dismissed

2022-01-28 15:01 UTC, rorysproule1 submitted a review, later dismissed

2022-01-31 08:17 UTC, dawidskainos requested changes

2022-01-31 08:17 UTC, dawidskainos commented on db-connector/src/main/java/uk/nhs/adaptors/connector/model/RequestStatus.java
>  public enum RequestStatus {
Maybe we could work on the names:
RequestStatus -> MigrationStatus
RECEIVED -> REQUEST_RECEIVED
EXTRACT_RECEIVED -> EHR_EXTRACT_RECEIVED
COMPLETED -> remove - we will add it when needed

2022-01-31 11:54 UTC, dawidskainos approved these changes

2022-01-31 12:03 UTC, rorysproule1 approved these changes

2022-01-31 12:05 UTC, merged