NIAD-1960: HL7 TS/IVL_TS to FHIR DateTime and Instant (updated to Fix previous PR)
NHSDigital/nia-patient-switching-standard-adaptor pull request #36
Opened 2022-01-26 15:10 UTC by AlanSimpson1723

2022-01-27 07:28 UTC, dawidskainos requested changes

2022-01-27 07:28 UTC, dawidskainos commented on gp2gp-translator/build.gradle
> +    implementation 'junit:junit:4.13.1'
junit is probably not needed here?

2022-01-27 07:28 UTC, dawidskainos commented on gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/util/DateUtilTest.java
> +public class DateUtilTest {
Would you mind changing these tests to read XML input - just like we did for few other resources in the project?

2022-01-28 10:38 UTC, rorysproule1 approved these changes

2022-01-28 12:12 UTC, dawidskainos approved these changes

2022-01-28 12:22 UTC, merged