NIAD-1854: MHS Mock
NHSDigital/nia-patient-switching-standard-adaptor pull request #5
Opened 2021-11-08 11:20 UTC by bbell-kainos

Initial setup of MHS mock directories

2021-11-08 12:43 UTC, dawidskainos requested changes
Could we rename it to "mhs-adaptor-mock"?

2021-11-09 08:44 UTC, dawidskainos requested changes
I noticed one more thing - gp2gp translator and gpc-facade are on root level. Maybe let's stick to that?

2021-11-09 09:27 UTC, ElliotB-96 approved these changes

2021-11-10 08:25 UTC, dawidskainos approved these changes

2021-11-10 08:26 UTC, mrogowska approved these changes

2021-11-10 08:26 UTC, merged