NIAD-1844: PSS Queue
NHSDigital/nia-patient-switching-standard-adaptor pull request #6
Opened 2021-11-17 09:47 UTC by bbell-kainos

2021-11-22 09:06 UTC, ElliotB-96 submitted a review, later dismissed

2021-11-22 10:37 UTC, dawidskainos requested changes

2021-11-22 10:37 UTC, dawidskainos commented on amqp-common/src/main/java/uk/nhs/adaptors/amqp/PublishQueue.java
> +public class PublishQueue {
Perhaps a different name - QueuePublisher?

2021-11-22 10:37 UTC, dawidskainos commented on amqp-common/src/main/java/uk/nhs/adaptors/amqp/PublishQueue.java
> +    private void sendToQueue(String destination, TaskDefinition taskDefinition) throws JmsException {
I think this should be a generic code - accepting queue name as param

2021-11-22 10:37 UTC, dawidskainos commented on amqp-common/src/main/java/uk/nhs/adaptors/amqp/SubscribeQueue.java
> +public class SubscribeQueue {
subscribes should probably be part of each app that handles messages
amqp-common should only common generic code for handling queues related operations

2021-11-22 10:37 UTC, dawidskainos commented on amqp-common/src/main/java/uk/nhs/adaptors/amqp/TestMainClass.java
> +public class TestMainClass {
should be removed?

2021-11-22 10:37 UTC, dawidskainos commented on amqp-common/src/main/java/uk/nhs/adaptors/amqp/task/TaskDefinition.java
> +    private final String taskId;
do we need all those fields? maybe it is a better idea to start adding them once we need them?

2021-11-22 10:37 UTC, dawidskainos commented on amqp-common/src/main/java/uk/nhs/adaptors/amqp/task/TaskType.java
> +public enum TaskType {
I'm not a fan of any "Test code" in production code. No one will ever remove it if we keep it.

2021-11-22 10:37 UTC, dawidskainos commented on amqp-common/src/main/resources/application.yml
> +amqp:
we should have separate configuration for mhs queue and pss queue - this is how NME will set it up probably

2021-11-25 07:31 UTC, dawidskainos requested changes

2021-11-25 07:31 UTC, dawidskainos commented on gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/amqp/PssQueueListener.java
> +@AllArgsConstructor
Can we replace AllArgs with @RequiredArgsConstructor(onConstructor = @__(@Autowired)) ?

2021-11-25 07:31 UTC, dawidskainos commented on gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/amqp/PssQueueListener.java
> +public class PssQueueListener {
Maybe PssQueueConsumer?

2021-11-25 07:31 UTC, dawidskainos commented on gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/amqp/PssQueueListener.java
> +    public void listenToPssQueue(Message message) {
Simply rename to receive? IT will then (in the future) delegate the received message to a handler class

2021-11-25 07:31 UTC, dawidskainos commented on gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/amqp/PssQueueListener.java
> +        //        TODO: Do Something
just use lombok logger to log incoming message?

2021-11-25 07:31 UTC, dawidskainos commented on gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/amqp/task/TaskDefinition.java
> +public class TaskDefinition {
what about getting rid of that class completely? maybe we could add it when we need it?

2021-11-25 07:31 UTC, dawidskainos commented on gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/amqp/task/TaskHandlerException.java
> +public class TaskHandlerException extends RuntimeException {
what about getting rid of that class completely? maybe we could add it when we need it?

2021-11-25 07:31 UTC, dawidskainos commented on gpc-api-facade/src/main/java/uk/nhs/adaptors/gpc/amqp/task/TaskDefinition.java
> +public class TaskDefinition {
what about getting rid of that class completely? maybe we could add it when we need it?

2021-11-25 07:31 UTC, dawidskainos commented on gpc-api-facade/src/main/java/uk/nhs/adaptors/gpc/amqp/task/TaskHandlerException.java
> +public class TaskHandlerException extends RuntimeException {
what about getting rid of that class completely? maybe we could add it when we need it?

2021-11-25 07:48 UTC, mrogowska requested changes

2021-11-25 07:48 UTC, mrogowska commented on gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/config/AmqpConfiguration.java
> +        if (!isEmpty(properties.getUsername())) {
IntelliJ shows that this `isEmpty` method is deprecated. Maybe you could use `properties.getUsername().isEmpty()` instead? Here and in others if statements in this class.

2021-11-25 08:23 UTC, mrogowska submitted a review, later dismissed

2021-11-25 09:51 UTC, mrogowska approved these changes

2021-11-25 09:55 UTC, dawidskainos approved these changes

2021-11-25 09:56 UTC, merged