NIAD-2046: Connect ConditionMapper to BundleMapperService
NHSDigital/nia-patient-switching-standard-adaptor pull request #66
Opened 2022-02-18 11:25 UTC by bchotkowski

Ticket -> [NIAD-2046](https://gpitbjss.atlassian.net/browse/NIAD-2046)

2022-02-22 14:20 UTC, mrogowska requested changes

2022-02-22 14:20 UTC, mrogowska commented on gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapper.java
> +            .forEach(linkSet -> {
The brackets can be removed

2022-02-22 14:25 UTC, bchotkowski commented on gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapper.java
> +                    .addIdentifier(buildIdentifier(id, "TEMP_PRACTICE_CODE")) //TODO: Find how to get the practise code legit way
The [NIAD-2021](https://gpitbjss.atlassian.net/browse/NIAD-2021) ticket specifies this requirement

2022-02-23 13:06 UTC, mrogowska approved these changes

2022-02-23 14:26 UTC, rorysproule1 approved these changes

2022-02-23 14:33 UTC, merged