NIAD-1843: Application DB setup
NHSDigital/nia-patient-switching-standard-adaptor pull request #7
Opened 2021-11-18 11:32 UTC by mrogowska

2021-11-18 12:00 UTC, dawidskainos requested changes

2021-11-18 12:00 UTC, dawidskainos commented on db-connector/config/checkstyle/checkstyle.xml
> +<?xml version="1.0"?>
would it be possible to have common config for all modules?

2021-11-18 12:00 UTC, dawidskainos commented on db-connector/src/main/java/uk/nhs/adaptors/connector/dao/PatientMigrationRequestDao.java
> +    @SqlUpdate("INSERT INTO public.patient_migration_request(id) VALUES (:id)")
Perhaps we could remove this one? I don't want anyone to get confused and think we're going to set IDs manually. Those should be set using sequence.

2021-11-18 12:00 UTC, dawidskainos commented on docker-compose.yml
> +            POSTGRES_HOST_AUTH_METHOD: "trust"
maybe we could use username/password combination?

2021-11-18 12:00 UTC, dawidskainos commented on db/setup-db.sql
> +CREATE USER pss;
Maybe we could create separate users for gpc-facade and gp2gp translator?

2021-11-18 12:00 UTC, dawidskainos commented on gpc-api-facade/src/main/resources/db/changelog/migration/01-create-patient_migration_request.sql
> +    id character varying(36) NOT NULL
2 comments here:
- maybe we should use liquibase syntax - to abstract from sepecific database?
- can we create sequence for ID column? and actually make it PK?

2021-11-18 12:00 UTC, dawidskainos commented on db/setup-db.sql
> +GRANT ALL PRIVILEGES ON DATABASE pss TO pss;
can we GRANT specific privileges, not ALL?

2021-11-18 12:00 UTC, dawidskainos commented on db-connector/src/main/java/uk/nhs/adaptors/connector/configuration/BaseConfiguration.java
> +        jdbiPlugins.forEach(jdbi::installPlugin);
should we add Postgres JDBI Plugin? 
https://jdbi.org/apidocs/org/jdbi/v3/postgres/PostgresPlugin.html

2021-11-18 12:00 UTC, dawidskainos commented on db/setup-db.sql
> +CREATE DATABASE pss WITH OWNER pss;
DB name - maybe patient_switching?

2021-11-22 10:00 UTC, dawidskainos requested changes

2021-11-22 10:52 UTC, bbell-kainos approved these changes

2021-11-22 10:59 UTC, merged