Dynamic generation of ignored JsonPaths
NHSDigital/nia-patient-switching-standard-adaptor pull request #71
Opened 2022-02-23 13:36 UTC by ElliotB-96

- Created util for dynamically generating ignored json paths

2022-02-23 13:50 UTC, rorysproule1 approved these changes

2022-02-23 14:19 UTC, rorysproule1 submitted a review, later dismissed

2022-02-23 14:23 UTC, bbell-kainos approved these changes

2022-02-24 07:58 UTC, mrogowska requested changes

2022-02-24 07:58 UTC, mrogowska commented on gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/EhrExtractHandlingIT.java
> +        IParser parser = context.newJsonParser();
I think you could use here existing FhirParser (from common module)

2022-02-24 07:58 UTC, mrogowska commented on gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/EhrExtractHandlingIT.java
> +            Stream.of(generateJsonPathIgnores(bundle), STATIC_IGNORED_JSON_PATHS)
Could you assign the result of the stream to a variable, and then pass the variable here? It would be more readable

2022-02-24 09:00 UTC, bbell-kainos approved these changes

2022-02-24 09:03 UTC, mrogowska approved these changes

2022-02-24 09:09 UTC, merged