NIAD-2015: Receive ack from MHS
NHSDigital/nia-patient-switching-standard-adaptor pull request #72
Opened 2022-02-24 16:02 UTC by mrogowska

2022-02-28 09:35 UTC, rorysproule1 approved these changes

2022-02-28 09:41 UTC, bbell-kainos requested changes

2022-02-28 09:41 UTC, bbell-kainos commented on gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/AcknowledgeMessageHandlingIT.java
> +        // process starts with consuming a message from MHS queue
Do we necessarily need these comments?

2022-02-28 09:41 UTC, bbell-kainos commented on gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/AcknowledgeMessageHandlingIT.java
> +        // process starts with consuming a message from MHS queue
Once again, are these comments needed?

2022-02-28 14:10 UTC, bbell-kainos approved these changes

2022-03-01 13:50 UTC, dawidskainos approved these changes

2022-03-01 13:51 UTC, merged